export const SET_MENU = "SET_MENU";
export const SET_APPETIZERS = "SET_APPETIZERS";
export const SET_BEVERAGES = "SET_BEVERAGES";
export const SET_ENTREES = "SET_ENTREES";
export const SET_DESSERTS = "SET_DESSERTS";
export const SET_FIVEDOLLARMEALS = "SET_FIVEDOLLARMEALS";

export const SET_CUSTOMER_ID = "SET_CUSTOMER_ID";

export const SET_ORDER_ID = "SET_ORDER_ID";